# Generated by Django 5.0 on 2023-12-17 19:38

import django.db.models.deletion
import web_dev.models.patient
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True, validators=[web_dev.models.patient.custom_email_validator])),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_1', models.CharField(default='Do you have any allergies?', max_length=200)),
                ('answer_1', models.CharField(blank=True, max_length=200)),
                ('question_2', models.CharField(default='Have you ever had surgery?', max_length=200)),
                ('answer_2', models.CharField(blank=True, max_length=200)),
                ('question_3', models.CharField(default='Are you currently taking any medication?', max_length=200)),
                ('answer_3', models.CharField(blank=True, max_length=200)),
                ('question_4', models.CharField(default='Do you have history of heart disease in your family?', max_length=200)),
                ('answer_4', models.CharField(blank=True, max_length=200)),
                ('question_5', models.CharField(default='Do you have a history of Diabetes in your family?', max_length=200)),
                ('answer_5', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_dev.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
