# Generated by Django 5.0 on 2023-12-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_dev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinformation',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='answer_5',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='question_3',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='question_4',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='question_5',
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='Allergies',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Do you have any allergies?', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='Heart_Disease_History',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Do you have history of heart disease in your family?', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='History_of_Diabetes',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Do you have a history of Diabetes in your family?', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='On_Medications',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Are you currently taking any medication?', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='Surgery',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Have you ever had surgery?', max_length=200),
        ),
    ]
